from pathlib import Path

from config.settings import DATA_DIR

DATA_SOURCE_SCHEMA_VERSION = "v2"

PROVIDER_DATA_DIR = DATA_DIR / "providers"

SCHWAB_PROVIDER_NAME = "schwab"
SCHWAB_PROVIDER_VERSION = "market-data-v1"
SCHWAB_DATA_DIR = PROVIDER_DATA_DIR / SCHWAB_PROVIDER_NAME / SCHWAB_PROVIDER_VERSION
SCHWAB_RAW_PAYLOAD_DIR = SCHWAB_DATA_DIR / "raw"
SCHWAB_NORMALIZED_DIR = SCHWAB_DATA_DIR / "normalized"
SCHWAB_MANIFEST_DIR = SCHWAB_DATA_DIR / "manifests"

YAHOO_BASELINE_NAME = "yahoo_phase_1_v1"
